export const en = {
  nav: 'Factory', title: 'Factory', work: 'Work', settings: 'Settings',
  search: 'Search tasks', empty: 'No Factory work matches this view.', emerging: 'Emerging sessions', leader: 'Scheduler leader',
  'emerging.settled': 'Settled emerging work', 'emerging.settledCount': 'Sessions · {count}', 'emerging.unsettle': 'Un-settle', 'emerging.unsettleTask': 'Un-settle {title}',
  project: 'Project', prompt: 'Agent prompt',
  attachments: 'Screenshots',
  'comment.queued': 'Queued · not steered', 'comment.steeredPending': 'Steered · waiting to post', 'comment.posted': 'Posted', 'comment.steered': 'Steered', 'comment.note': 'Saved note', 'comment.you': 'You', 'comment.agent': 'Agent', 'comment.system': 'System', 'comment.empty': 'No comments or follow-up prompts yet.', 'comment.edit': 'Edit queued prompt', 'comment.save': 'Save queued prompt', 'comment.cancel': 'Cancel editing', 'comment.remove': 'Remove queued prompt', 'comment.moveEarlier': 'Move prompt earlier', 'comment.moveLater': 'Move prompt later', 'comment.steerNow': 'Steer now', 'comment.queuePrompt': 'Queue prompt', 'comment.sendPrompt': 'Send prompt', 'comment.placeholderPrompt': 'Add a prompt or steer the running agent…', 'comment.placeholderConnecting': 'Connecting to the task Session…', 'comment.placeholderNote': 'Leave a comment…', 'comment.hintQueue': 'Cmd/Ctrl+Enter queues · Shift+Cmd/Ctrl+Enter steers', 'comment.hintConnecting': 'Waiting for the active task Session', 'comment.connecting': 'Connecting…', 'comment.hintNote': 'Cmd/Ctrl+Enter to comment', 'comment.questionTitle': 'Agent needs your answer', 'comment.questionHint': 'This task and its dependent work stay paused until you respond.', 'comment.answerQuestion': 'Answer in Session',
  'changes.changed': 'Changed files ({count})', 'changes.changedOne': 'Changed file (1)', 'changes.viewFileDiff': 'View diff for {name}', 'changes.expandFolders': 'Expand all', 'changes.collapseFolders': 'Collapse all', 'changes.viewDiff': 'View diff', 'image.pending': 'Untitled image', 'image.remove': 'Remove image {name}', 'image.group': 'Task images', 'image.open': 'Preview original image', 'image.openNamed': 'Preview original image {name}', 'image.loading': 'Loading image…', 'image.loadFailed': 'Image unavailable · retry', 'image.scrollLeft': 'Scroll images left', 'image.scrollRight': 'Scroll images right', 'image.preview': 'Original image preview', 'image.closePreview': 'Close original image preview', 'image.previous': 'Previous', 'image.next': 'Next', 'image.position': '{current} of {total}', dependencies: 'Dependencies', activity: 'Activity', comments: 'Comments', addComment: 'Add comment', edit: 'Edit', save: 'Save',
  back: 'Back to work', queue: 'Queue', pause: 'Pause', retry: 'Retry', stop: 'Cancel', attach: 'Attach session', output: 'Output',
  disposition: 'Task visibility', settle: 'Settle', settled: 'Settled', archive: 'Archive', archived: 'Archived',
  refresh: 'Refresh', loading: 'Loading Factory…', close: 'Close', status: 'Status', preset: 'Preset', model: 'Model', customPath: 'Workspace path', remove: 'Remove', dependsOn: 'Depends on',
  'intake.task': 'Task', 'intake.taskDetail': 'Start and capture this Session in Emerging work', 'intake.runNow': 'Run immediately', 'intake.runNowDetail': 'Send normally and capture the live Session', 'intake.runLater': 'Run later', 'intake.runLaterDetail': 'Create a draft without starting the Session', 'intake.flow': 'Flow', 'intake.flowDetail': 'Create or join a dependency flow', 'intake.newFlow': 'New flow', 'intake.newFlowDetail': 'Use this task as the first node', 'intake.back': 'Back', 'intake.loading': 'Loading flows…', 'intake.parallel': 'Parallel branch', 'intake.parallelDetail': 'Run independently inside the flow', 'intake.sequential': 'After current work', 'intake.sequentialDetail': 'Depend on every current leaf node', 'intake.finalizer': 'Finalizer', 'intake.finalizerDetail': 'Always run after current leaf nodes', 'intake.aria': 'New work intent, current {intent}',
} as const

export const zh: Record<keyof typeof en, string> = {
  nav: '工厂', title: '任务工厂', work: '工作', settings: '设置',
  search: '搜索任务', empty: '当前视图中没有匹配的任务。', emerging: '涌现中的会话', leader: '调度器主节点',
  'emerging.settled': '已结涌现工作', 'emerging.settledCount': '会话 · {count}', 'emerging.unsettle': '取消结算', 'emerging.unsettleTask': '取消结算 {title}',
  project: '项目', prompt: '代理提示',
  attachments: '截图',
  'comment.queued': '已排队 · 尚未插话', 'comment.steeredPending': '已插话 · 等待发布', 'comment.posted': '已发布', 'comment.steered': '已插话', 'comment.note': '已保存备注', 'comment.you': '你', 'comment.agent': '代理', 'comment.system': '系统', 'comment.empty': '还没有评论或后续提示。', 'comment.edit': '编辑排队提示', 'comment.save': '保存排队提示', 'comment.cancel': '取消编辑', 'comment.remove': '移除排队提示', 'comment.moveEarlier': '提前提示', 'comment.moveLater': '延后提示', 'comment.steerNow': '立即插话', 'comment.queuePrompt': '排队提示', 'comment.sendPrompt': '发送提示', 'comment.placeholderPrompt': '添加提示或插话运行中的代理…', 'comment.placeholderConnecting': '正在连接任务会话…', 'comment.placeholderNote': '留下评论…', 'comment.hintQueue': 'Cmd/Ctrl+Enter 排队 · Shift+Cmd/Ctrl+Enter 插话', 'comment.hintConnecting': '正在等待活动任务会话', 'comment.connecting': '连接中…', 'comment.hintNote': 'Cmd/Ctrl+Enter 添加评论', 'comment.questionTitle': '代理需要你的回答', 'comment.questionHint': '此任务及其依赖工作将在你回答前保持暂停。', 'comment.answerQuestion': '在会话中回答',
  'changes.changed': '已更改文件（{count}）', 'changes.changedOne': '已更改文件（1）', 'changes.viewFileDiff': '查看 {name} 的差异', 'changes.expandFolders': '展开全部', 'changes.collapseFolders': '收起全部', 'changes.viewDiff': '查看差异', 'image.pending': '未命名图片', 'image.remove': '移除图片 {name}', 'image.group': '任务图片', 'image.open': '预览原图', 'image.openNamed': '预览原图 {name}', 'image.loading': '正在加载图片…', 'image.loadFailed': '图片不可用 · 重试', 'image.scrollLeft': '向左滚动图片', 'image.scrollRight': '向右滚动图片', 'image.preview': '原图预览', 'image.closePreview': '关闭原图预览', 'image.previous': '上一张', 'image.next': '下一张', 'image.position': '第 {current} 张，共 {total} 张', dependencies: '依赖', activity: '活动', comments: '评论', addComment: '添加评论', edit: '编辑', save: '保存',
  back: '返回工作列表', queue: '排队', pause: '暂停', retry: '重试', stop: '取消', attach: '关联会话', output: '输出',
  disposition: '任务可见性', settle: '归入已结', settled: '已结', archive: '归档', archived: '已归档',
  refresh: '刷新', loading: '正在加载工厂…', close: '关闭', status: '状态', preset: '预设', model: '模型', customPath: '工作区路径', remove: '删除', dependsOn: '依赖于',
  'intake.task': '任务', 'intake.taskDetail': '启动会话并捕获到涌现工作', 'intake.runNow': '立即运行', 'intake.runNowDetail': '正常发送并捕获活动会话', 'intake.runLater': '稍后运行', 'intake.runLaterDetail': '创建草稿但不启动会话', 'intake.flow': '流程', 'intake.flowDetail': '创建或加入依赖流程', 'intake.newFlow': '新建流程', 'intake.newFlowDetail': '以此任务作为第一个节点', 'intake.back': '返回', 'intake.loading': '正在加载流程…', 'intake.parallel': '并行分支', 'intake.parallelDetail': '在流程中独立运行', 'intake.sequential': '接续当前工作', 'intake.sequentialDetail': '依赖所有当前叶节点', 'intake.finalizer': '收尾任务', 'intake.finalizerDetail': '始终在当前叶节点之后运行', 'intake.aria': '新工作意图，当前为 {intent}',
}

declare module '@monotykamary/dsh-client-ui-slots' {
  interface LocaleNamespaceMap { factory: keyof typeof en }
}
